### ISSUE TITLE
Tracking Issue `Berlin Hardfork`

### ISSUE THREAD

**Issue by niklasad1** [openethereum/openethereum#11562]
Tracking issue for [Berlin EIPs](https://eips.ethereum.org/EIPS/eip-2070) implementation progress, when it is gonna happen is not scheduled yet (rough estimate June 2020)

Tentatively Accepted EIPs:

- [ ] [EIP-663](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-663.md): Unlimited SWAP and DUP instructions
   - Status: Not implemented
   - Estimate: might have issues https://ethereum-magicians.org/t/eip-663-unlimited-swap-and-dup-instructions/3346/23 
- [ ] [EIP-1057](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-663.md): ProgPoW, a Programmatic Proof-of-Work
   - Status: Implemented (https://github.com/openethereum/openethereum/pull/9762)
   - Estimate: Unknown (pending audit)
 - [ ] [EIP-1380](https://eips.ethereum.org/EIPS/eip-1380): Reduced gas cost for call to self
   - Status: Not implemented
   - Estimate: Unknown, https://ethereum-magicians.org/t/eip-1380-reduced-gas-cost-for-call-to-self/1242/21
 - [ ] [EIP-1702](https://eips.ethereum.org/EIPS/eip-1702): Generalized account versioning scheme
   - Status: Implemented (https://github.com/openethereum/openethereum/pull/10771)
   - Estimate: Unknown
 - [ ] [EIP-1962](https://eips.ethereum.org/EIPS/eip-1702): EC arithmetic and pairings with runtime definitions
        replaces EIP-1829
   - Status: Not implemented
   - Estimate: Unknown, depends on `BLS precompile` I guess. Libraries exist already in Rust
 - [ ]  [EIP-1985](https://eips.ethereum.org/EIPS/eip-1985): Sane limits for certain EVM parameters
   - Status: Not implemented
   - Estimate: Unknown
 - [ ] [EIP-2045](https://eips.ethereum.org/EIPS/eip-2045): Particle gas costs for EVM opcodes
   - Status: Not implemented
   - Estimate: Unknown
 - [ ] [EIP-2046](https://eips.ethereum.org/EIPS/eip-2046): Reduced gas cost for static calls made to precompiles

Feel free to edit and this issue if you have more information.
This is just a starting point to keep track of it.
