### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by adria0** [openethereum/openethereum#11647]
At this moment current OE tests need to be improved (draft PR https://github.com/openethereum/openethereum/pull/11597)

- [x]  https://github.com/openethereum/openethereum/issues/10461 If chain specs are not defined, the tests pass. Implemented in https://github.com/openethereum/openethereum/pull/11597/commits/ed33e5392d915954ec86b726a28e16c215edda27 https://github.com/openethereum/openethereum/pull/11597/commits/227c1be3f7b9ca5e1da7b81e5ae24f6dcb75de0a
- [x] `postState` is not verified in BlockchainTests, implemented in https://github.com/openethereum/openethereum/pull/11597/commits/ff6c4150e24ea5386964d36bdb826bf925793a1d
- [x] https://github.com/OpenEthereum/open-ethereum/issues/11078 https://github.com/OpenEthereum/open-ethereum/pull/10923 fix `stRevertTests` 
- [x] https://github.com/openethereum/openethereum/issues/11129 Tests need to be updated to `v7`. Implemented in https://github.com/openethereum/openethereum/pull/11597/commits/8bfba8115095707301b1a43accbd6b6cd3122ab9
- [x] ~~We are using the last [develop branch](https://github.com/openethereum/openethereum/blob/master/.gitmodules) of [ethereum/tests](https://github.com/ethereum/tests/tree/develop). The idea is to fix it to a specific commit because now this approach has three problems~~
  - ~~It can break the builds any time~~
  - ~~Is not possible to have a reproducible build&test, this makes checking for regressions more complex~~
  - ~~Currently geth, that is the filler of the tests, is using [another branch](https://github.com/ethereum/go-ethereum/blob/master/.gitmodules), so even not geth is using `develop` to test the tests generated with retesteth.~~
- [x] https://github.com/openethereum/openethereum/issues/11085  Now we need to change and sync the code and manually sync the tests, because folders are hardcoded. It is better just to scan the folders and run tests.
