### ISSUE TITLE
Backport xDAI support

### ISSUE THREAD

**Issue by adria0** [openethereum/openethereum#118]
POSDAO PRs:

- https://github.com/openethereum/parity-ethereum/pull/10909
- https://github.com/openethereum/parity-ethereum/pull/10902
- https://github.com/openethereum/parity-ethereum/pull/11379
- https://github.com/openethereum/parity-ethereum/pull/10803
- https://github.com/openethereum/parity-ethereum/pull/10529
- https://github.com/openethereum/parity-ethereum/pull/10920
- https://github.com/openethereum/parity-ethereum/pull/10916
 

non POSDAO related pull requests but mostly regarding forks of PoA networks

- https://github.com/openethereum/parity-ethereum/pull/10606
- https://github.com/openethereum/parity-ethereum/pull/10628
- https://github.com/openethereum/parity-ethereum/pull/10989
- https://github.com/openethereum/parity-ethereum/pull/11068
- https://github.com/openethereum/parity-ethereum/pull/11236
- https://github.com/openethereum/parity-ethereum/pull/11282
- https://github.com/openethereum/parity-ethereum/pull/11298
- https://github.com/openethereum/parity-ethereum/pull/11299
- https://github.com/openethereum/parity-ethereum/pull/11411
- https://github.com/openethereum/parity-ethereum/pull/11505
- https://github.com/openethereum/parity-ethereum/pull/11609
- https://github.com/openethereum/parity-ethereum/pull/11610
- https://github.com/openethereum/parity-ethereum/pull/11611

**Comment by rakita** [comment]
Will start backporting in number order:

- [ ] openethereum/parity-ethereum#10529
- [ ] openethereum/parity-ethereum#10803
- [ ] openethereum/parity-ethereum#10902
- [ ] openethereum/parity-ethereum#10909
- [ ] openethereum/parity-ethereum#10916
- [ ] openethereum/parity-ethereum#10920
- [ ] openethereum/parity-ethereum#11379

will pust changes to this branch: https://github.com/rakita/openethereum/commits/xdai

**Comment by rakita** [comment]
This is another list of commits that we got from @varasev: 
- [ ] openethereum/parity-ethereum/pull/10875
- [ ] openethereum/parity-ethereum/pull/10928
- [ ] openethereum/parity-ethereum/pull/10946
- [ ] openethereum/parity-ethereum/pull/11160
- [ ] openethereum/parity-ethereum/pull/11170
- [ ] openethereum/parity-ethereum/pull/11245

**Comment by varasev** [comment]
Hi @rakita 

While comparing the changes in https://github.com/rakita/openethereum/commit/161a587789f0cc094433c648cd9e4a09b095ba2d with the original ones from https://github.com/openethereum/parity-ethereum/pull/10529/files I noticed that the file `ethcore/src/engines/authority_round/mod.rs` in the `sealing_state` function contains different code for assigning `client` variable:

Lines from https://github.com/rakita/openethereum/commit/161a587789f0cc094433c648cd9e4a09b095ba2d:

```rust
        let client = match self.upgrade_client_or("Not preparing block") {
            Ok(client) => client,
            Err(_) => return SealingState::NotReady,
        };
```

and original lines from https://github.com/openethereum/parity-ethereum/pull/10529/files#diff-8f5994565965bcc4142e6948f4be3f6343474f722db22548117cced6cac5ab76:

```rust
		let client = match self.client.read().as_ref().and_then(|weak| weak.upgrade()) {
			Some(client) => client,
			None => {
				warn!(target: "engine", "Not preparing block: missing client ref.");
				return SealingState::NotReady;
			}
		};
```

**Comment by varasev** [comment]
@rakita Ah, sorry, that's fine. I didn't take into account changes in further commits

**Comment by varasev** [comment]
@rakita Please, add the following lines to `on_close_block` function in your branch after [this line](https://github.com/rakita/openethereum/blob/22342f4a10b0866a22139ea0c2bf0fdd7725993a/ethcore/src/engines/authority_round/mod.rs#L1813):

```rust
if let Some(signer) = self.signer.read().as_ref() {
    let our_addr = signer.address();
    self.validators.on_close_block(&block.header, &our_addr)?
}
```

During retesting `reportMalicious` feature I found that our former rust developer forgot to add these lines to call [`on_close_block` function in `ethcore/src/engines/validator_set/multi.rs`](https://github.com/rakita/openethereum/blob/22342f4a10b0866a22139ea0c2bf0fdd7725993a/ethcore/src/engines/validator_set/multi.rs#L104).

**Comment by rakita** [comment]
Merged 🎉
