### ISSUE TITLE
Replace the Websockets Server

### ISSUE THREAD

**Issue by 5chdn** [openethereum/openethereum#7032]
Swap out the web-sockets server

- [ ] #3544 Websockets queue gets full
- [x] #6326 DB corrupted due to 'cannot access stderr during shutdown'
- [x] #6405 Parity performance problem with Ledger attached/contract usage.

^ Ideally, a new ws server addresses these issues.

**Comment by rphmeier** [comment]
cc @tomusdrw : can you describe which server you were intending to replace the existing with?

**Comment by tomusdrw** [comment]
I would give https://github.com/snapview/tokio-tungstenite/ a shot.

https://github.com/cyderize/rust-websocket has tokio APIs as well, but seems to be using old version of hyper (0.10), so it's a no-go for now.

Same issues in jsonrpc repo: https://github.com/paritytech/jsonrpc/issues/158

**Comment by rakita** [comment]
Closing issue due to its stale state.
